### PR TITLE
Fix the incorrect task.next() before the step function for the asynch…

### PR DESCRIPTION
**Pull request by blacktail**
After some test, i find the task.next function call before the step function may be redundant and incorrect.

### CODE REVIEW

**Comment by nzakas** [comment]
Hmm, I don't believe this is correct. You must call next() once to start the iterator.

**Comment by blacktail** [comment]
Here is my test code, i change the fs.read to setTimeout for run the test in Browser. 

```javascript
function run(taskDef) {
    "use strict";
    // create the iterator
    let task = taskDef();

    // start the task
    task.next();

    // recursive function to iterate through
    (function step() {

        let result = task.next(),
            promise;

        console.log('in step, result is', result);
        // if there's more to do
        if (!result.done) {

            // resolve to a promise to make it easy
            promise = Promise.resolve(result.value);
            promise.then(function(value) {
                task.next(value);
                step();
            }).catch(function(error) {
                task.throw(error);
                step();
            });
        }
    }());
}

function readConfigFile() {
    return new Promise(function (resolve, reject) {
        setTimeout(function () {
            resolve('this is config file contents');
        }, 500);
    });
}

function doSomethingWith(contents) {
    console.log('doSomethingWith: ', contents);
}

run(function *() {
    "use strict";
    let contents = yield readConfigFile();
    doSomethingWith(contents);
    console.log("Done");
});
```

Below is the output:
254156bf-6a7e-4d4e-b1b2-0dc1dd814692

And if i remove these code:
```
// start the task
task.next();
```

The output is:
fa050c3f-a159-4b1e-b4f0-cd8eb6cec43d

So i think we do not need an additional task.next to start the iterator

**Comment by getify** [comment]
Since `let result = task.next()` runs inside `step()`, I am fairly certain @blacktail is correct that the `task.next()` outside/above the `step()` definition is in fact unnecessary.

Moreover, I think the `run(..)` as specified is incorrect in other ways... if I'm reading correctly, these two lines:

```js
task.next(value);
step();
```

... in the `promise.then(..)` handler will result in `task.next(..)` being called twice right in a row, which is incorrect. For reference, I [have a runner](https://github.com/getify/You-Dont-Know-JS/blob/master/async%20&%20performance/ch4.md#promise-aware-generator-runner) that I believe has been tested to work correctly.

**Comment by blacktail** [comment]
Hi @getify @nzakas , i have updated the PR, and now fix the task.next twice call problem.

**Comment by getify** [comment]
@blacktail also need to address the `task.throw(error)`, I think.

**Comment by blacktail** [comment]
Definitely, addressed

**Comment by nzakas** [comment]
Thanks! Can you also update the description of the code in the paragraph that follows?

**Comment by blacktail** [comment]
Updated

**Comment by getify** [comment]
FWIW, this sentence reads a little awkwardly:

"Inside of `step()`, first to check the iterator result."

**Comment by blacktail** [comment]
Yes, forgive my english, how about remove this sentence "first to check the iterator result.":

Inside of `step()`, if there's more work to do then `result.done` is `false`.

**Comment by getify** [comment]
Sounds much better. :)

**Comment by nzakas** [comment]
That's good. I'll also clarify it when I do further edits, just didn't want to forget.

Thanks!

**Pull request merged**
